name: "CryptoApp"
options:
  bundleIdPrefix: com.hoangkhoachau
  deploymentTarget:
    iOS: "17.0"

packages:
  Inject:
    url: https://github.com/krzysztofzablocki/Inject.git
    from: 1.5.2
targets:
  CryptoApp:
    type: application
    platform: iOS
    sources: 
    - path: Sources/CryptoApp
      excludes: [Info.plist]
    resources: 
    - path: Sources/CryptoApp/Source
      excludes: [Info.plist]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.hoangkhoachau.CryptoApp"
      ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
      SWIFT_VERSION: "5.0" # Update to the version you're using
      OTHER_LDFLAGS:
        - "-Xlinker"
        - "-interposable"
    info:
      path: Sources/CryptoApp/Source/Info.plist
      properties:
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UISupportedInterfaceOrientations~ipad:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
    dependencies:
      - package: Inject
  CryptoApp_Unit_Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/CryptoApp_Unit_Tests]
    dependencies:
      - target: CryptoApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.hoangkhoachau.CryptoApp_Unit_Tests"
      SWIFT_VERSION: "5.0"
      GENERATE_INFOPLIST_FILE: YES

  CryptoApp_UI_Tests:
    type: bundle.ui-testing
    platform: iOS
    sources: [Sources/CryptoApp_UI_Tests]
    dependencies:
      - target: CryptoApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.hoangkhoachau.CryptoApp_UI_Tests"
      SWIFT_VERSION: "5.0"
      GENERATE_INFOPLIST_FILE: YES

configurations:
  Debug:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      ENABLE_PREVIEWS: YES
  Release:
    buildSettings:
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"

schemes:
  CryptoApp:
    build:
      targets:
        CryptoApp: all
        CryptoApp_Unit_Tests: all
        CryptoApp_UI_Tests: all
    run:
      config: Debug
    test:
      config: Debug
